name: disco_app
description: Disco music app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  dio: ^5.2.1+1
  audio_session: ^0.1.16
  flutter_bloc: ^8.1.3
  flutter_facebook_auth: ^6.0.0
  flutter_svg: ^2.0.7
  auto_route: ^7.7.0
  cached_network_image: ^3.2.3
  freezed: ^2.3.5
  get_it: ^7.6.0
  flutter_secure_storage: ^8.0.0
  injectable: ^2.1.2
  injectable_generator: ^2.1.6
  pretty_dio_logger: ^1.3.1
  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.3
  pull_to_refresh: 2.0.0
  just_audio: ^0.9.34
  video_player: ^2.7.0
  flutter_native_splash: ^2.3.1
  chewie: ^1.6.0+1
  provider: ^6.0.5
  sign_in_with_apple: ^5.0.0
  marquee: ^2.2.3
#  signalr_netcore: 1.3.3
  web_socket_channel: ^2.4.0
  file_picker: ^5.3.2
  image_picker: ^1.0.0
  infinite_scroll_pagination: 3.2.0
  path_provider: ^2.0.15
  http: ^1.1.0
#  flutter_chat_ui: 1.6.8
  #  cube_transition:
  #    git:
  #      url: https://github.com/t4ulabs/cube_transition.git
  #      ref: NullSafetyUpgrade # branch name
  flutter_launcher_icons: ^0.13.1
  swipeable_page_route: ^0.4.0
  google_sign_in: ^6.1.4
  flutter_staggered_grid_view: 0.6.2
  objectbox: 1.7.0
  objectbox_flutter_libs: any
  signalr_pure: ^1.1.0
  leak_detector: ^1.0.1+4
  equatable: ^2.0.5

#  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  objectbox_generator: 1.7.0
  auto_route_generator: ^7.2.0
  flutter_lints: ^2.0.2

flutter:
  fonts:
    - family: Colonna
      fonts:
        - asset: fonts/ColonnaMT.ttf
          weight: 700
  assets:
    - assets/



uses-material-design: true

