name: disco_app
description: Disco music app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.4
  google_fonts: 2.2.0
  dio: 4.0.4
  audio_session: 0.1.6+1
  flutter_bloc: 8.0.0
  flutter_facebook_auth: 4.0.1
  flutter_svg: 1.0.3
  auto_route: 2.3.2
  cached_network_image: 3.2.0
  freezed: 1.1.0
  get_it: 7.2.0
  flutter_secure_storage: 5.0.2
  injectable: 1.5.3
  injectable_generator: 1.5.2
  pretty_dio_logger: 1.2.0-beta-1
  carousel_slider: 4.0.0
  percent_indicator: 4.0.0
  pull_to_refresh: 2.0.0
  just_audio: 0.9.20
  video_player: 2.2.7
  flutter_native_splash: 1.3.2
  chewie: 1.3.2
  provider: 6.0.2
  sign_in_with_apple: 3.3.0
  marquee: 2.2.1
  signalr_netcore: 1.2.6
  web_socket_channel: 2.2.0
  file_picker: 5.2.4
  image_picker: 0.8.6
  infinite_scroll_pagination: 3.2.0
  #  cube_transition:
  #    git:
  #      url: https://github.com/t4ulabs/cube_transition.git
  #      ref: NullSafetyUpgrade # branch name
  flutter_launcher_icons: 0.10.0
  swipeable_page_route: 0.2.6
  google_sign_in: 5.3.1
  flutter_staggered_grid_view: 0.6.2
  objectbox: 1.6.2

#  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  objectbox_generator: ^1.3.0
  auto_route_generator: 2.3.2
  flutter_lints: ^1.0.4

flutter:
  fonts:
    - family: Colonna
      fonts:
        - asset: fonts/ColonnaMT.ttf
          weight: 700
  assets:
    - assets/



uses-material-design: true

